/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"

/* Header for class com_pitaya_dll_BsDiffUtil */

#ifndef _Included_com_pitaya_dll_BsDiffUtil
#define _Included_com_pitaya_dll_BsDiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pitaya_dll_BsDiffUtil
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pitaya_dll_BsDiffUtil_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
